### ISSUE TITLE
Read from stdin

### ISSUE THREAD

**Issue by glazari** [nicolascouvrat/javaimports#60]
A lot of formatting tools offer the option to receive the file from stdin instead of receiving a filepath to open. This plays well with text-editors like vim where you might want to format the contents of the file without saving.

Examples of tools that offer this features:
- `goimports`
- `gofmt`
- `rustfmt`
- `google-java-format`

The first to will default to read from stdin if no file is provided and the last one interprets a `-` filepath argument as meaning stdin. Either one seems like a reasonable choice.

I will probably implement this feature for myself, if you agree that this feature could be usefull I could open a PR for it.

**Comment by nicolascouvrat** [comment]
Hey!

Thank you very much for the feedback. This sound really reasonable to me, I'll be glad to review your PR.

Also note that I just released a (long overdue) [new version](https://github.com/nicolascouvrat/javaimports/releases/tag/javaimports-parent-1.2) you might want to check it out as it comes with a bunch of bug fixes and new features 😄

**Comment by glazari** [comment]
Wow, thanks for the quick response!
great to see a new version coming out! I'm kind of new to java, so I might take a while with this PR. But coming from Go I'm very happy to have found your project, thank you!

**Comment by glazari** [comment]
I've created this PR https://github.com/nicolascouvrat/javaimports/pull/62

So far this has covered my use case quite well! :) But I'll be glad to hear your feedback and apply any changes if needed

**Comment by nicolascouvrat** [comment]
Hello again, sorry for the super late response... I have not had much time to work on javaimports lately. Thank you very much for your PR, it looks good! I'll bundle it in the next release 🙇

**Comment by nicolascouvrat** [comment]
Fixed with #62
